name: complex-epidemics-simulator
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - numpy
  - matplotlib
  - jupyter
  - pandas
  - mesa
  - networkx
  - black
  - pylint
  - attrs
  - pytest
  - pytest-cov
  - ipympl
  - scipy
  - seaborn

